# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KxTeRMDaooc5wI6d8DNnXlk1pveOsqoI
"""

# step 1 : import library
import pandas as pd

# step 2 : import data
cancer = pd.read_csv('https://raw.githubusercontent.com/YBIFoundation/Dataset/main/Cancer.csv')

cancer.head()

cancer.info()

cancer.describe()

# step 3:define target (y) and  features(x)

cancer.columns

y = cancer['diagnosis']

x = cancer.drop(['id', 'diagnosis','Unnamed: 32'],axis=1)

# step 4 :train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,train_size=0.7,random_state=2529)

X_train.shape,X_test.shape,y_train.shape,y_test.shape

# step 5:select model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=5000)

# step 6 : train  or fit model
model.fit(X_train,y_train)

model.intercept_

model.coef_

# step 7:predict model
y_pred = model.predict(X_test)

y_pred

# step 8 : model accuracy
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

confusion_matrix(y_test,y_pred)

accuracy_score(y_test,y_pred)

print(classification_report(y_test,y_pred))